### ISSUE TITLE
romeo: unable to sign and broadcast withdrawal tx

### ISSUE THREAD

**Issue by EmbeddedAndroid** [stacks-network/sbtc#236]
### Expected Behavior

Withdrawal works

### Actual Behavior

Did we miss the need to fund the an STX wallet address for the withdrawal?

```
023-10-05T18:45:57.758618Z  INFO spawn: romeo::system: Spawning task=FetchStacksBlock(19)
2023-10-05T18:46:07.675968Z  INFO update: romeo::state: Processing event=BitcoinBlock(459)
2023-10-05T18:46:07.676321Z  INFO spawn: romeo::system: Spawning task=FetchBitcoinBlock(460)
2023-10-05T18:46:07.772721Z  INFO update: romeo::state: Processing event=StacksBlock(19)
2023-10-05T18:46:07.772756Z  INFO spawn: romeo::system: Spawning task=FetchStacksBlock(20)
2023-10-05T18:46:17.682263Z  INFO update: romeo::state: Processing event=BitcoinBlock(460)
2023-10-05T18:46:17.682702Z  INFO spawn: romeo::system: Spawning task=FetchBitcoinBlock(461)
2023-10-05T18:46:17.682759Z  INFO spawn: romeo::system: Spawning task=CreateBurn(WithdrawalInfo { txid: f1d1642ed8ad078c661399a2b0ed1354f83cdb0e052f06f3ceb1683b3ec3b2d2, amount: 1571, source: Standard(StandardPrincipalData(ST2ST2H80NP5C9SPR4ENJ1Z9CDM9PKAJVPYWPQZ50)), recipient: bcrt1q3zl64vadtuh3vnsuhdgv6pm93n82ye8q6cr4ch, block_height: 460 })
2023-10-05T18:46:18.171978Z  INFO update: romeo::state: Processing event=StacksBlock(20)
2023-10-05T18:46:18.172014Z  INFO spawn: romeo::system: Spawning task=FetchStacksBlock(21)
2023-10-05T18:46:18.190559Z  INFO update: romeo::state: Processing event=BurnBroadcasted(WithdrawalInfo { txid: f1d1642ed8ad078c661399a2b0ed1354f83cdb0e052f06f3ceb1683b3ec3b2d2, amount: 1571, source: Standard(StandardPrincipalData(ST2ST2H80NP5C9SPR4ENJ1Z9CDM9PKAJVPYWPQZ50)), recipient: bcrt1q3zl64vadtuh3vnsuhdgv6pm93n82ye8q6cr4ch, block_height: 460 }, e759e0cda56bb61bec66374fb0e30db400338226d72c0a812e5387bbaa2f42fd)
2023-10-05T18:46:27.687335Z  INFO update: romeo::state: Processing event=BitcoinBlock(461)
2023-10-05T18:46:27.687664Z  INFO spawn: romeo::system: Spawning task=FetchBitcoinBlock(462)
2023-10-05T18:46:28.210440Z  INFO update: romeo::state: Processing event=StacksBlock(21)
2023-10-05T18:46:28.210472Z  INFO spawn: romeo::system: Spawning task=FetchStacksBlock(22)
2023-10-05T18:46:28.210508Z  INFO spawn: romeo::system: Spawning task=CheckStacksTransactionStatus(e759e0cda56bb61bec66374fb0e30db400338226d72c0a812e5387bbaa2f42fd)
2023-10-05T18:46:37.692904Z  INFO update: romeo::state: Processing event=BitcoinBlock(462)
2023-10-05T18:46:37.693239Z  INFO spawn: romeo::system: Spawning task=FetchBitcoinBlock(463)
2023-10-05T18:46:38.224218Z  INFO update: romeo::state: Processing event=StacksBlock(22)
2023-10-05T18:46:38.224249Z  INFO spawn: romeo::system: Spawning task=FetchStacksBlock(23)
2023-10-05T18:46:38.241767Z  INFO update: romeo::state: Processing event=StacksTransactionUpdate(e759e0cda56bb61bec66374fb0e30db400338226d72c0a812e5387bbaa2f42fd, Confirmed)
2023-10-05T18:46:47.698699Z  INFO update: romeo::state: Processing event=BitcoinBlock(463)
2023-10-05T18:46:47.699019Z  INFO spawn: romeo::system: Spawning task=FetchBitcoinBlock(464)
2023-10-05T18:46:48.256686Z  INFO update: romeo::state: Processing event=StacksBlock(23)
2023-10-05T18:46:48.256746Z  INFO spawn: romeo::system: Spawning task=FetchStacksBlock(24)
2023-10-05T18:46:48.256802Z  INFO spawn: romeo::system: Spawning task=CreateFulfillment(WithdrawalInfo { txid: f1d1642ed8ad078c661399a2b0ed1354f83cdb0e052f06f3ceb1683b3ec3b2d2, amount: 1571, source: Standard(StandardPrincipalData(ST2ST2H80NP5C9SPR4ENJ1Z9CDM9PKAJVPYWPQZ50)), recipient: bcrt1q3zl64vadtuh3vnsuhdgv6pm93n82ye8q6cr4ch, block_height: 460 })
2023-10-05T18:46:57.704511Z  INFO update: romeo::state: Processing event=BitcoinBlock(464)
2023-10-05T18:46:57.704859Z  INFO spawn: romeo::system: Spawning task=FetchBitcoinBlock(465)
2023-10-05T18:46:58.300145Z  INFO update: romeo::state: Processing event=StacksBlock(24)
2023-10-05T18:46:58.300180Z  INFO spawn: romeo::system: Spawning task=FetchStacksBlock(25)
2023-10-05T18:47:01.305810Z  INFO bdk::wallet: Derivation of 1 addresses from 0 took 0 ms
2023-10-05T18:47:01.305895Z  INFO bdk::wallet: Derivation of 1 addresses from 0 took 0 ms
2023-10-05T18:47:01.329542Z  INFO bdk::blockchain::script_sync: finished setup, elapsed 2ms
thread 'tokio-runtime-worker' panicked at 'Unable to sign and broadcast the withdrawal fulfillment transaction: Insufficient funds: 0 sat available of 1659 sat needed', romeo/src/system.rs:404:10
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at ./rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at ./rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/result.rs:1651:5
   3: romeo::system::run_task::{{closure}}
   4: romeo::system::spawn::{{closure}}
   5: tokio::runtime::task::core::Core<T,S>::poll
   6: tokio::runtime::task::harness::Harness<T,S>::poll
   7: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
   8: tokio::runtime::scheduler::multi_thread::worker::Context::run
   9: tokio::runtime::context::scoped::Scoped<T>::set
  10: tokio::runtime::context::runtime::enter_runtime
  11: tokio::runtime::scheduler::multi_thread::worker::run
  12: tokio::runtime::task::core::Core<T,S>::poll
  13: tokio::runtime::task::harness::Harness<T,S>::poll
  14: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
### Steps to Reproduce

Using latest devenv from `main`

**Comment by friedger** [comment]
Yes, sbtc wallet sends the broadcast tx

**Comment by AshtonStephens** [comment]
Looking into this now

**Comment by AshtonStephens** [comment]
I'll test this locally today and close if it's not a problem for me.

**Comment by friedger** [comment]
The funding issue has been solved. 

The error for `Got an Rejected status update for a Stacks transaction that is not acknowledged` should be a new issue if we think this is happens on testnet or devnet again.
