### ISSUE TITLE
[sBTC DR] Romeo crashes with unexpected transaction status updates

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc#268]
### Expected Behavior
Romeo runs stable (See #262 )

### Actual Behavior
Romeo crashes with the message below:

```
thread 'main' panicked at 'Got an Rejected status update for a Stacks transaction that is not acknowledged: 49cc171922c389e11bf53640d3c4d3d83c04c0701cd232c451c84c9c03232b03', romeo/src/state.rs:293:29
```
### Steps to Reproduce
TBD

**Comment by radicleart** [comment]
see also issue https://github.com/stacks-network/sbtc/issues/262

**Comment by radicleart** [comment]
See also

```
thread 'main' panicked at 'Got an Broadcasted status update for a Stacks transaction that is not acknowledged: f14325bdaefdf4d982892204ffa9a6ec2188e5d0a44685d5f58c4ca97d3db570', romeo/src/state.rs:293:29
```

**Comment by stjepangolemac** [comment]
I think we had a bad auto merge somewhere.
